version: '3.3'
services:
    frickl:
        image: frickl
        environment:
          - JAVA_OPTS:-Xmx512m
        ports:
          - 80:8080
        volumes:
          - type: volume
            source: frickl
            target: /usr/local/tomcat/webapps
          - type: bind
            source: ./images
            target: /data/images
        restart: unless-stopped
        container_name: frickl

    mysql:
        image: mysql:5.7
        volumes:
          - type: volume
            source: mysql
            target: /var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: FricklIsAwesome
          MYSQL_DATABASE: frickl
          MYSQL_USER: frickl
          MYSQL_PASSWORD: frickl
        restart: unless-stopped
        container_name: frickl-mysql

volumes:
    frickl:
    mysql:
          
